setNum = set()
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))
setNum.add(input("Input  Number :"))

print(setNum)